export const kidsMenuItems = [
  { id: 'k1', name: "Spidey Sliders", tagline: "Mini burgers with web-shaped cheese!", price: 9.5, calories: 380, time: 8, emoji: '🍔', desc: 'Two mini beef sliders with melted cheddar cut into web shapes, lettuce, ketchup on soft buns', allergens: ['Gluten', 'Dairy'], color: '#e03030' },
  { id: 'k2', name: "Web-Slinger Pizza", tagline: "Red sauce webs on a crispy base!", price: 10, calories: 420, time: 14, emoji: '🍕', desc: 'Mini pizza with marinara, mozzarella and tomato paste webs, topped with pepperoni spots', allergens: ['Gluten', 'Dairy'], color: '#1a4fa0' },
  { id: 'k3', name: "Peter's Pasta", tagline: "Spaghetti that looks like webs!", price: 8.5, calories: 340, time: 10, emoji: '🍝', desc: 'Spaghetti in a mild tomato sauce shaped into a web, with hidden veggie meatballs', allergens: ['Gluten'], color: '#e03030' },
  { id: 'k4', name: "Hero Hot Dog", tagline: "Even heroes need a hot dog!", price: 7, calories: 290, time: 6, emoji: '🌭', desc: 'Beef frankfurter in a soft roll with ketchup, mustard, and a little spider flag pick', allergens: ['Gluten'], color: '#1a4fa0' },
  { id: 'k5', name: "Webbed Waffle Fries", tagline: "Criss-cross fries just like webs!", price: 6, calories: 260, time: 7, emoji: '🍟', desc: 'Crispy waffle-cut fries lightly salted, served with ketchup and a blue cheese dip', allergens: [], color: '#e03030' },
  { id: 'k6', name: "Spider Nuggets", tagline: "Crispy chicken with spider shapes!", price: 8, calories: 310, time: 9, emoji: '🍗', desc: '6 crispy chicken nuggets in spider shapes, served with sweet and sour sauce', allergens: ['Gluten'], color: '#1a4fa0' },
  { id: 'k7', name: "MJ's Garden Wrap", tagline: "Eat your veggies, save the day!", price: 7.5, calories: 240, time: 6, emoji: '🌯', desc: 'Soft tortilla with hummus, cucumber, carrot ribbons, cherry tomatoes and cheddar', allergens: ['Gluten', 'Dairy'], color: '#e03030' },
  { id: 'k8', name: "Web Sundae", tagline: "The sweetest finish to a heroic meal!", price: 6.5, calories: 320, time: 3, emoji: '🍨', desc: 'Vanilla ice cream with chocolate web sauce, red sprinkles and a wafer spider', allergens: ['Dairy', 'Gluten'], color: '#1a4fa0' },
];
